### ISSUE TITLE
Take the system configuration into account

### ISSUE THREAD

**Issue by jfsmig** [open-io/oiopy#17]
Using the environment is a nice improvement over the previous SDK.

But the current backend relies on a set of files (/etc/oio/sds.conf, ...) and it would be nice the oiopy SDK to also take those files into account.

I don't know if environment should override the system configuration (or the opposite).

**Comment by jkasarherou** [comment]
Ok for loading settings from system files (sds.conf).
I think it would be better if the env/cli settings override the system configuration

**Comment by jfsmig** [comment]
Ok for `sys < env < cli`

**Comment by jkasarherou** [comment]
ok fixed in #24
