### ISSUE TITLE
"openio account create" requires inexistant support in the oio-proxy

### ISSUE THREAD

**Issue by jfsmig** [open-io/oiopy#18]
The execution of the command "aacount create" invariably ends on an error.

    jfs@localhost 48 # openio -v account create ACCT
    command: account create -> oiopy.cli.storage.account.CreateAccount
    Using parameters {'proxyd_url': 'http://127.0.0.1:6002', 'namespace': 'NS', 'account_name': 'ACCT'}
    n/a (HTTP 404)

It seems the required route is absent from the oio-proxy (cf. the accesslog below):

    Aug 17 20:44:23 localhost OIO,NS,proxy[19666]: 19666 D140 access INF 127.0.0.1:6002 127.0.0.1:56740 GET 404 0.000093 0 - /v3.0/lb/NS/account t=0.000058

**Comment by jkasarherou** [comment]
fixed in #27
